stages:
  - build
  - test
  - package
  - push

build-binary:
    image: golang:1.22.0-alpine
    stage: build
    script:
        - apk add --no-cache git
        - git --version
        - git clone https://gitlab.oit.duke.edu/devil-ops/patchmonkeyctl.git
        - cd patchmonkeyctl
        - go build ./cmd/patchmonkeyctl
        - mv patchmonkeyctl ../
    artifacts:
      paths:
        - patch
        

check-architecture:
    stage: test
    script:
        - file patchmonkeyctl