stages:
  - package

package_image:
  image: docker:cli
  stage: package
  services:
    - name: docker:dind
      command: ["--registry-mirror", "https://pull-through.cloud.duke.edu/"]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info
    - echo $DOCKER_HOST
  script:
    - pwd
    - ls
    - tree
    - docker build -t gitlab-registry.oit.duke.edu/vn74/patchmoney-docker .
    - docker push gitlab-registry.oit.duke.edu/vn74/patchmoney-docker